version: '3.8'

services:
  ai-app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: nest-app
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    ports:
      - '3000:3000' # Application Port
    volumes:
      - ./src:/app/src
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge
